import { useState } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import { FileText, X, Copy, CheckCircle, Download, Printer } from 'lucide-react'
import { getCurrency } from '../../stores/settingsStore'

function ContractGenerator({ isOpen, onClose, creator, campaign }) {
    const [form, setForm] = useState({
        brandName: campaign?.brand || '',
        creatorName: creator?.name || '',
        deliverables: campaign?.creators?.find(c => c.creatorId === creator?.id)?.deliverables?.map(d => `${d.quantity} ${d.type}`).join(', ') || '',
        rate: campaign?.creators?.find(c => c.creatorId === creator?.id)?.totalFee || '',
        upfrontPercent: 50,
        platform: campaign?.platform || 'Instagram',
        startDate: campaign?.startDate || '',
        endDate: campaign?.endDate || '',
        exclusivityDays: 30,
        usageRights: 'Brand may repost content on own channels for 90 days',
        revisions: 2,
        paymentMethod: 'Bank Transfer',
    })
    const [copied, setCopied] = useState(false)

    const sym = getCurrency().symbol

    const contractText = `
INFLUENCER MARKETING AGREEMENT
${'='.repeat(50)}

DATE: ${new Date().toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' })}
AGREEMENT NO: INF-${Date.now().toString().slice(-6)}

PARTIES:
- BRAND: ${form.brandName || '[Brand Name]'} (hereinafter "Brand")
- CREATOR: ${form.creatorName || '[Creator Name]'} (hereinafter "Creator")

${'─'.repeat(50)}

1. SCOPE OF WORK

Creator agrees to create and publish the following content:
- Deliverables: ${form.deliverables || '[Specify deliverables]'}
- Platform: ${form.platform}
- Campaign Period: ${form.startDate || '[Start Date]'} to ${form.endDate || '[End Date]'}

2. COMPENSATION

- Total Fee: ${sym}${Number(form.rate).toLocaleString('en-IN') || '[Amount]'}
- Payment Schedule:
  * ${form.upfrontPercent}% (${sym}${Math.round(Number(form.rate) * form.upfrontPercent / 100).toLocaleString('en-IN')}) upon contract signature
  * ${100 - form.upfrontPercent}% (${sym}${Math.round(Number(form.rate) * (100 - form.upfrontPercent) / 100).toLocaleString('en-IN')}) upon content delivery & approval
- Payment Method: ${form.paymentMethod}

3. CONTENT REQUIREMENTS

- All content must comply with Brand guidelines provided separately
- Maximum ${form.revisions} revision(s) included in the fee
- Additional revisions: ${sym}${Math.round(Number(form.rate) * 0.05).toLocaleString('en-IN')} per revision
- Content must include proper disclosure (#ad, #sponsored, #paidpartnership)
- Creator must tag Brand's official account

4. CONTENT APPROVAL PROCESS

- Creator submits draft content for Brand review
- Brand provides feedback within 48 hours
- Creator implements revisions within 24 hours
- Final approval required before publishing

5. EXCLUSIVITY

- Creator shall NOT promote competing products/brands for ${form.exclusivityDays} days
  from the date of last published content.
- Competing brands are defined as brands in the same product category.

6. USAGE RIGHTS

- ${form.usageRights}
- Creator retains ownership of original content
- Brand may use content for internal reporting and case studies

7. CANCELLATION POLICY

- Either party may cancel with 7 days written notice
- If Brand cancels after work begins: Creator receives payment for completed deliverables
- If Creator cancels: Creator refunds any advance payment received

8. CONFIDENTIALITY

- Both parties agree to keep campaign details confidential until public launch
- Campaign performance data is shared between both parties

9. GOVERNING LAW

This agreement is governed by the laws of India.

${'─'.repeat(50)}

SIGNATURES:

Brand Representative: ____________________
Name: ${form.brandName || '[Brand Name]'}
Date: _______________

Creator: ____________________
Name: ${form.creatorName || '[Creator Name]'}
Date: _______________

${'─'.repeat(50)}
Generated by Sic CRM - Influencer Marketing Platform
`.trim()

    function handleCopy() {
        navigator.clipboard.writeText(contractText)
        setCopied(true)
        setTimeout(() => setCopied(false), 2000)
    }

    function handlePrint() {
        const win = window.open('', '_blank')
        win.document.write(`<html><head><title>Contract - ${form.creatorName}</title><style>body{font-family:monospace;padding:40px;line-height:1.6;max-width:800px;margin:0 auto}@media print{body{padding:20px}}</style></head><body><pre>${contractText}</pre></body></html>`)
        win.document.close()
        win.print()
    }

    if (!isOpen) return null

    return (
        <AnimatePresence>
            <motion.div className="inf-modal-overlay" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} onClick={onClose}>
                <motion.div className="cg-modal" initial={{ scale: 0.9 }} animate={{ scale: 1 }} exit={{ scale: 0.9 }} onClick={e => e.stopPropagation()}>
                    <div className="inf-modal-header">
                        <h2><FileText size={20} /> Contract Generator</h2>
                        <button onClick={onClose}><X size={20} /></button>
                    </div>

                    <div className="cg-layout">
                        {/* Input Form */}
                        <div className="cg-form-panel">
                            <h3>Contract Details</h3>
                            <div className="cg-form">
                                <div className="inf-form-group"><label>Brand Name</label>
                                    <input value={form.brandName} onChange={e => setForm(f => ({ ...f, brandName: e.target.value }))} /></div>
                                <div className="inf-form-group"><label>Creator Name</label>
                                    <input value={form.creatorName} onChange={e => setForm(f => ({ ...f, creatorName: e.target.value }))} /></div>
                                <div className="inf-form-group"><label>Deliverables</label>
                                    <input value={form.deliverables} onChange={e => setForm(f => ({ ...f, deliverables: e.target.value }))} placeholder="e.g., 2 Reels + 3 Stories" /></div>
                                <div className="inf-form-group"><label>Total Fee ({getCurrency().symbol})</label>
                                    <input type="number" value={form.rate} onChange={e => setForm(f => ({ ...f, rate: e.target.value }))} /></div>
                                <div className="inf-form-group"><label>Upfront %</label>
                                    <select value={form.upfrontPercent} onChange={e => setForm(f => ({ ...f, upfrontPercent: Number(e.target.value) }))}>
                                        <option value={25}>25%</option><option value={50}>50%</option><option value={75}>75%</option><option value={100}>100%</option>
                                    </select></div>
                                <div className="inf-form-group"><label>Platform</label>
                                    <select value={form.platform} onChange={e => setForm(f => ({ ...f, platform: e.target.value }))}>
                                        <option>Instagram</option><option>YouTube</option><option>Twitter</option><option>LinkedIn</option><option>TikTok</option>
                                    </select></div>
                                <div className="inf-form-group"><label>Start Date</label>
                                    <input type="date" value={form.startDate} onChange={e => setForm(f => ({ ...f, startDate: e.target.value }))} /></div>
                                <div className="inf-form-group"><label>End Date</label>
                                    <input type="date" value={form.endDate} onChange={e => setForm(f => ({ ...f, endDate: e.target.value }))} /></div>
                                <div className="inf-form-group"><label>Exclusivity (days)</label>
                                    <input type="number" value={form.exclusivityDays} onChange={e => setForm(f => ({ ...f, exclusivityDays: Number(e.target.value) }))} /></div>
                                <div className="inf-form-group"><label>Max Revisions</label>
                                    <input type="number" value={form.revisions} onChange={e => setForm(f => ({ ...f, revisions: Number(e.target.value) }))} /></div>
                            </div>
                        </div>

                        {/* Preview */}
                        <div className="cg-preview-panel">
                            <div className="cg-preview-header">
                                <h3>Contract Preview</h3>
                                <div className="cg-preview-actions">
                                    <button className="cg-action-btn" onClick={handleCopy}>
                                        {copied ? <><CheckCircle size={14} /> Copied!</> : <><Copy size={14} /> Copy</>}
                                    </button>
                                    <button className="cg-action-btn" onClick={handlePrint}>
                                        <Printer size={14} /> Print
                                    </button>
                                </div>
                            </div>
                            <pre className="cg-contract-text">{contractText}</pre>
                        </div>
                    </div>

                    <style>{`
                        .cg-modal { width: 95vw; max-width: 1200px; max-height: 90vh; overflow-y: auto; background: var(--bg-primary); border: 1px solid rgba(255,255,255,0.1); border-radius: 20px; }
                        .cg-layout { display: grid; grid-template-columns: 320px 1fr; gap: 20px; padding: 0 24px 24px; }
                        .cg-form-panel h3, .cg-preview-header h3 { font-size: 0.9rem; margin-bottom: 14px; color: var(--text-primary); }
                        .cg-form { display: flex; flex-direction: column; gap: 10px; }
                        .cg-preview-panel { min-width: 0; }
                        .cg-preview-header { display: flex; justify-content: space-between; align-items: center; flex-wrap: wrap; gap: 8px; }
                        .cg-preview-actions { display: flex; gap: 8px; }
                        .cg-action-btn {
                            display: flex; align-items: center; gap: 6px; padding: 6px 12px;
                            background: rgba(99,102,241,0.15); border: 1px solid rgba(99,102,241,0.3);
                            border-radius: 8px; color: var(--accent-primary); font-size: 0.75rem; cursor: pointer;
                        }
                        .cg-action-btn:hover { background: rgba(99,102,241,0.25); }
                        .cg-contract-text {
                            background: rgba(30,30,45,0.8); border: 1px solid rgba(255,255,255,0.06);
                            border-radius: 12px; padding: 20px; font-size: 0.8rem; color: var(--text-secondary);
                            line-height: 1.6; white-space: pre-wrap; font-family: 'Courier New', monospace;
                            max-height: 60vh; overflow-y: auto;
                        }
                        @media (max-width: 900px) { .cg-layout { grid-template-columns: 1fr; } }
                    `}</style>
                </motion.div>
            </motion.div>
        </AnimatePresence>
    )
}

export default ContractGenerator
